### ISSUE TITLE
JOSS PUBLICATION

### ISSUE THREAD

**Issue by chrklemm** [SESMG/SESMG#157]
**Code of Conduct**
- [x] Hereby I consent to the [CODE_OF_CONDUCT](https://github.com/SESMG/SESMG/blob/master/CODE_OF_CONDUCT.md)

The following tasks must be done for the final publication on 30.04.2023 (assignees/due date):

Status of 22.02.2023:

- [x] create running example model definition (@GregorBecker,  24.02.2023)
- [x] DOCU:  Check if system graph of upscaling is up to date #123 (@chrklemm, 24.02.2023)
- [x] STREAMLIT: US GUI result page #141 (@janik257, 10.03.2023)
- [x] STREAMLIT: Result Processing Start Page #141 (@janik257, 10.03.2023)
- [x] STREAMLIT: Demo-Tool-Start-Page #141 (@jtock, 10.03.2023)
- [x] DOCU: Describe pareto optimization (methodology) #123 (@chrklemm, 17.03.2023)  
- [x] STREAMLIT: Demo-Tool-Results #141 (@jtock, 27.03.2023)
- [x] complete draft of manuscript (@chrklemm, 31.03.2023)
- [x] correct manuscript (@GregorBecker, @jtock, 31.03.2023)
- [x] INSTALLATION: Windows: Update and verify all steps #155 (@GregorBecker @janik257 @chrklemm , 31.03.2023) 
- [x] INSTALLATION: Windows: Instruction Video #155 (@GregorBecker @janik257 @chrklemm , 31.03.2023)
- [x] INSTALLATION: MacOS Intel Chip: Update and verify all steps (@GregorBecker, 31.03.2023)
- [x] INSTALLATION: MacOS M1/M2 Chip: Instruction Video #155 (@GregorBecker @jtock , 31.03.2023) - Status: Problems with new iOS, new Deadline 14.04.2023
- [x] INSTALLATION: MacOS M1/M2 Chip: Update and verify all steps #140 (@GregorBecker + @jtock, 31.03.2023) Status: Problems with new iOS, new Deadline 14.04.2023
- [x] DOCU: Streamlit GUI #123 (@janik257, 31.03.2023)
- [x] DOCU: Switch Criterion #123 (@janik257, 31.03.2023)
- [x] DOCU: Update Docu-Main-Page + README.md #123 (@janik257 @chrklemm, 31.03.2023)
- [x] DOCU: Include Screenshots for new GUI #123 (@janik257, 31.03.2023)
- [x] DOCU: Include description of heuristic selection schemes (technical data section) #123 (@chrklemm, 31.03.2023) 
- [x] DOCU: Write Introduction of Application Section #123 (@janik257, 31.03.2023) 
- [x] DOCU: Describe Result Outputs in Streamlit GUI #123 (@janik257 @jtock, 31.03.2023) 
- [x] DOCU: Re-Write Demo-Tool-Description regarding the new Streamlit integration #123 (@jtock @benblankenstein , 31.03.2023) 
- [x] DOCU: Describe how the gurobi solver can be used (@chrklemm, 31.03.2023)
- [x] DEMO-Tool: Verify functionality of the Streamlit-Demo-Tool #130 (@jtock, 31.03.2023) 
- [x] DOCU: Unify Wording #143 (@chrklemm, 31.03.2023)
- [x] STREAMLIT: Unify Wording #143 (@jtock, 31.03.2023)
- [x] STREAMLIT: Test and Review the new GUI (@chrklemm, 07.04.2023) 
- [x] MANUSCRIPT: Correct references (@jtock, 07.04.2023) 
- [x] README: Unify installation instructions in docu and readme (@GregorBecker, @jtock, 07.04.2023)
- [x] Move TK-Inter to own branch (@GregorBecker, 07.04.2023)
- [x] STREAMLIT: Result Processing Results/Sub-Results #141 (@jtock @GregorBecker , 07.04.2023)
- [x] DOCU: Restructure Streamlit-Docu -> integrate sections into sub-chapters of the application-chapter (@chrklemm, @jtock,  14.04.2023)
- [x] BUGFIX: wind turbines without production #166 (@GregorBecker, 14.04.2023)
- [x] INSTALLATION: Linux: Update and verify all steps (@GregorBecker, 14.04.2023, MEDIUM)  
- [x] DOCU: Update technical data section #123 (@GregorBecker, 14.04.2023)
- [x] FEATURE: Time-system (UTC, MEZ, MESZ)-Column Sheet for model definition #156 (@GregorBecker, 14.04.2023, LOW/MEDIUM)  
- [x] BUGFIX: Fix error in constraint equation #151 (@GregorBecker, 14.04.2023, HIGH)
- [x] DOCU: complete API documentation #123 (@GregorBecker, 14.04.2023)
- [x] DOCU: write docstrings for "data preparation" and "pre-modeling" and "Spreadsheet-Energy-System-Model-Generator(@chrklemm, 14.04.2023) 
- [x] DOCU: check API documentation #123 (@GregorBecker, 14.04.2023)
- [x] DOCU: Update introduction of API-documentation section #123 (@GregorBecker, 14.04.2023) 
- [x] DOCU: add documentation for timezone column in energy system spreadsheet(@GregorBecker)
- [x] MANUSCRIPT: review manuscript (@eguvep , 21.04.2023)
- [x] BUGFIX: #159 (@jtock )
- [x] RESUTS: #170 (@jtock , @GregorBecker)

---------------------------------------------------------------------------------------------------------------------------------

TODO Before submission on 12.05.2023
- [x] write short descriptions in "comment" column for insulation and  (@GregorBecker)   
- [x] Release new version  (@GregorBecker @chrklemm)   
- [x] Check all open issues (@GregorBecker @chrklemm)   
- [x] Transfer open/not relevant to-do-list entries into wishlist issues  (@GregorBecker @chrklemm)   
- [x] Answer to open discussions  (@GregorBecker @chrklemm)   

No must do's:
- [x] write short descriptions in "comment" column of model definitions (@GregorBecker, @benblankenstein, no deadline)   
- [x] INSTALLATION: Windows: Graphviz Installation via Pip Win #150 (@GregorBecker, no deadline) 
- [x] CODE: Unify Wording #143 (@GregorBecker, 31.03.2023)
- [x] DEMO: Include variable DH Network, update parameters, update docu, review changes (@benblankenstein) 
- [x] EXAMPLE: update and expand the example + description (@benblankenstein)

**Comment by jtock** [comment]
Needs to be checked if we match the JOSS requirements. 
"Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems)." 
https://joss.readthedocs.io/en/latest/review_checklist.html

**Comment by chrklemm** [comment]
I did a quick review of the streamlit-gui, as @jtock and I discussed last week. It is way more intuative than the tk-inter gui. Thank you again for the effort of developing it. However, I have some minor comments:

1. Within the result-folder there is a file called "TODO.md" which is listed in the result-drop-down-menu. Do we need this file? Or can we re-name it? This file might be confusing for new users.
2. Some of the help-comments are missing (https://github.com/SESMG/SESMG/blob/master/program_files/GUI_st/GUI_st_help_comments.json) - do you need further information to complete them? @jtock 
3. I wasn't able to find the function for creating the energy system graph WITHOUT having to process the entire model. Is it not included within streamlit?
4. We should consider re-naming the field of  "Pareto Point Options" to "Multi-Objective Optimization" to unify wording with the documentation
5. Energy Amount-Diagrams: the plots are not very robust if other model definitions than the urban-upscaling ones is used  (right @GregorBecker ?). Should we possibly add a corresponding note in the gui?
6. Demo: Efficiencies for the chp are labeled as "???". The efficiencies should be added @benblankenstein 

Questions / No action needed if not possible:
- Is it possible to zoom within the energy system graph (results)?
- It is necessary to upload the model-definition for each model run, right? Even if the same model-definition is used for several model runs?
- Is it possible to directly transfer an upscaled-model-definition to the processing?

**Comment by jtock** [comment]
Thank you for reviewing @chrklemm!

- [ ] 1. I gave it a quick fix and opened an issue for that.
- [ ] 2. It would be perfect if you add the three missing positions @chrklemm!
- [ ] 3. This function is not implemented. We have listed this on the #152 .
- [x] 4. Done - good idea!
- [x] 5. There is a comment which addresses this.
- [x] 6. Will be done within the bullet points in the upper issue.

Questions
1. This is also on #152 .
2. That is right. We did no find a way to do this. It is on #152 to store the last file.
3. That could be possible, but is not realy matching to the multi-page approach. Switching the pages could be possible, but then we end in question 2 again. Added to #152

**Comment by chrklemm** [comment]
> * [x]  2. It would be perfect if you add the three missing positions @chrklemm!

done @jtock

**Comment by chrklemm** [comment]
I just added the missing docstrings for "data_preparation" and "pre-model-analysis". @GregorBecker is this satisfying the requirements or do you need further assistance regardings this point?
