### ISSUE TITLE
Things to be done to be able to merge dev into master 

### ISSUE THREAD

**Issue by GregorBecker** [SESMG/SESMG#217]
**Code of Conduct**
- [x] Hereby I consent to the [CODE_OF_CONDUCT](https://github.com/SESMG/SESMG/blob/master/CODE_OF_CONDUCT.md)[^1]

- [x] Enable functionality of the SESMG examples
- [x] Update the SESMG examples
- [x] check Documentation
- [x] documentation of anergy networks #142 
- [x] merge timeseries links (update to the current sesmg version) 
- [x] merge timeseries links (documentation) 
- [x] check US Tool functionality
- [ ] document new US Tool components
- [ ] Fix variable cost factor #208 
- [x] Documentation of multi competition constraints #165 
- [x] modelling with a heat network is currently only running with a pre-calculation 

[^1]: Fill in a x between the brackets to check the check box.

**Comment by jtock** [comment]
Fix versioning to v1.1.0

- [ ] Update installation docu (delete old version, add warning)
- [ ] Add missing points in docu
- [ ] Test examples
- [ ] Test new functions (LCA, Demo)
- [ ] Open issue for bug in application installation

- [ ] Update to v1.1.0
- [ ] Deploy new dev branch
